#!/bin/bash
#gets userID, listID, task

read -p "userID: " userID
read -p "listID: " listID
read -p "taskID: " taskID
read -p "Port: " port
curl -i -H "Content-Type: application/json" -X DELETE -d '{"userID": "'$userID'", "listID": "'$listID'", "taskID": "'$taskID'"}' -b cookie-jar -k https://info3103.cs.unb.ca:$port/users/$userID/lists/$listID/tasks/$taskID
